operation scripting

diff --git a/management/bash/clRunner b/management/bash/clRunner
--- a/management/bash/clRunner
+++ b/management/bash/clRunner
@@ -100,6 +100,11 @@ if [ "$parameterFileName" = "all" ]; then
 else
 	pushd $parameterFolderPath > /dev/null
 	parameterFileList=($(ls $parameterFileName* ))
+
+	if [ "$parameterFileList" = "" ]; then
+		echo -e "\n\nERROR: There are no parameter files in the specified location ($parameterFolderPath/$parameterFileName). Perhaps you didn't run cmAssembleParameterFiles";
+		exit $?
+	fi
 	popd  > /dev/null
 fi
 
